### ISSUE TITLE
Kurze Frage

### ISSUE THREAD

**Issue by PhilipKyleBoone** [DHBeng/HexagonLamp#4]
Hey Dennis,

ich habe dir zwar in Thingiverse geschrieben, aber weil es eher eine Frage des Codes ist, dachte ich, ich schreibe dich auch hier an. Und dann habe ich bemerkt, dass du Deutsch kannst, also schreibe ich dich mal in Deutsch an... auch wenn es nicht meine Muttersprache ist :) also sorry für die ganze Grammatikalische Fehler.

Ich habe bzw. möchte eine Lampe mit 7 Hexagon erstellen, anstatt nur 6. Damit es quasi Symmetrisch ist. Dafür muss ich die Verkabelung etwas anpassen. (sehe angehängtes Foto)

Meine Haupt Frage ist es, wie kann ich die LAMP_DEF Konstante so anpassen, dass die 9 zusätzliche LED's (ledpositions) drin passen? Ich habe nicht ganz verstanden, wie man die X und Y Pos der LED's ermittelt. Ich meine, es ist klar, dass ich die NUMPIXELS auf 96 erhöhen muss, und, dass ich 6 weitere ledposition Strukturen benötige... aber wie gesagt, ich weis nicht wie du auf die X,Y Positionen der LED's gekommen bist. Und noch eine Frage: wenn ich die Verkabelung ändere... funktioniert noch die X,Y alle LED's noch? Anders gesagt, hat die Reihenfolge der verlötete Einzelstreifen Auswirkung auf der X,Y ?

Ich hänge eine Foto der Lampe an, so wie ich es bauen möchte.

Ich danke dir für deine Zeit! 

![IMG_6315](https://user-images.githubusercontent.com/18245410/151702051-89a921d6-992b-4aad-8bbd-85bca219fbf7.JPG)

**Comment by DHBeng** [comment]
Hey,
das array LAMP_DEF ist wie folgt auf gebaut: {led_ID,PosX, PosY}.
* led_ID: nummer der LED im Neopixel steifen; hängt von der Verdrahtung ab
* PosX: X position
* PosY: Y position

Zum Thema wie ich die Positionen und IDs ermittelt habe, hoffe ich dass das angehängte Bild deine Frage beantwortet.
![image](https://user-images.githubusercontent.com/77641517/151705981-1d86fb1f-f453-4d93-adad-c9a854e2a38c.png)

**Comment by PhilipKyleBoone** [comment]
Hallo lieber Dennis!

ja, das hilft! Habe jetzt kapiert denke ich. Das sind wohl die (ca.) Millimeter Positionen der LED's :) Cool. 

ich habe an sowas in der Richtung gedacht. Also ein Grid drüber legen, und dann dort wo X und Y sich kreuzen die Zahlen nehmen... nur ich wäre nie drauf gekommen, dass das Millimeter sind :) Obwohl, wenn man den Zeichnungen in den PDF'S genau betrachtet... wird es dann offensichtlicher. 

Lieben Dank!
